stages:
#  - prepare
  - Build-OSVVM
  - Build-PoC
  - Simulate
  - Documentation
  - GitLabPages

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  SIMULATOR_PAGES:        "nvc"      # simulator from which the results should be published on GitLab pages (GHDL, Riviera-PRO)

# --------------------
# ---- Templates -----
# --------------------
.run:
  script:
    - |
      if [[ "${SIMULATOR_TOOL}" == "NVC" ]]; then
        CreateAndChangeDirectory "temp/NVC" "Simulation working directory"
        # before_script and script are running in the same shell; therefore no need to change the directory
        REGRESSION_STEP=${STEP} nvc --do ../../regression.tcl
      else
        REGRESSION_STEP=${STEP} exec-${SIMULATOR_TOOL}.sh -n --tcl-file=regression.tcl
      fi
  after_script:
    - mkdir -p temp/junit
    - CopyFile temp/${SIMULATOR_TOOL}/*/*.xml "temp/junit"
    - CopyFile temp/${SIMULATOR_TOOL}/*/*.yml "temp/junit"
    - rm -vrf temp/${SIMULATOR_TOOL}/VHDL_LIBS/${SIMULATOR_TOOL}-*/TB_*
    - tree temp
  artifacts:
    paths:
      - temp/[GNR]*
      - temp/junit
      - lib/osvvm/*_generated.vhd
    reports:
      junit: "temp/junit/*.xml"
    expire_in: 1 week
    when: always

# ---------------
# ---- GHDL -----
# ---------------
OSVVM-build:
  extends:
    - .run
  stage: Build-OSVVM
  image: ${CI_REGISTRY}/docker-images/${IMAGE}:${VERSION}
  parallel:
    matrix:
      - IMAGE:     "rivierapro"
        VERSION:   "2024.10"
      - IMAGE:     "nvc"
        VERSION:   "latest"
      - IMAGE:     "ghdl"
        VERSION:   ["llvm", "mcode"]
  variables:
    STEP: "osvvm"

PoC-build:
  extends:
    - .run
  stage: Build-PoC
  image: ${CI_REGISTRY}/docker-images/${IMAGE}:${VERSION}
  parallel:
    matrix:
      - IMAGE:     "rivierapro"
        VERSION:   "2024.10"
      - IMAGE:     "nvc"
        VERSION:   "latest"
      - IMAGE:     "ghdl"
        VERSION:   ["llvm", "mcode"]
  needs:
    - job: OSVVM-build
      artifacts: true
      parallel:
        matrix:
          - IMAGE: $[[ matrix.IMAGE ]]
            VERSION: $[[ matrix.VERSION ]]
  variables:
    STEP: "poc"

.OSVVM-sim:  # step has to be added to regression.tcl
  extends:
    - .run
  stage: Simulate
  image: ${CI_REGISTRY}/docker-images/${IMAGE}:${VERSION}
  parallel:
    matrix:
      - IMAGE:     "rivierapro"
        VERSION:   "2024.10"
      - IMAGE:     "nvc"
        VERSION:   "latest"
      - IMAGE:     "ghdl"
        VERSION:   ["llvm", "mcode"]
  needs:
    - job: OSVVM-build
      artifacts: true
      parallel:
        matrix:
          - IMAGE: $[[ matrix.IMAGE ]]
            VERSION: $[[ matrix.VERSION ]]
  only:
    - main
    - master
    - dev
  variables:
    STEP: "osvvm_test"  # todo: add this to regression.tcl

PoC-sim:
  extends:
    - .run
  stage: Simulate
  image: ${CI_REGISTRY}/docker-images/${IMAGE}:${VERSION}
  parallel:
    matrix:
      - IMAGE:     "rivierapro"
        VERSION:   "2024.10"
      - IMAGE:     "nvc"
        VERSION:   "latest"
      - IMAGE:     "ghdl"
        VERSION:   ["llvm", "mcode"]
  needs:
    - job: PoC-build
      artifacts: true
      parallel:
        matrix:
          - IMAGE: $[[ matrix.IMAGE ]]
            VERSION: $[[ matrix.VERSION ]]
  allow_failure: true
  variables:
    STEP: "test"

# --------------------------
# ----- Documentation ------
# --------------------------
MergeReports:
  stage: Documentation
  image: ${CI_REGISTRY}/docker-images/base-image:alpine
  needs:
    - job: PoC-sim
      artifacts: true
  before_script:
    - pip install pyEDAA.Reports
  script:
    - mkdir -p report/unit
    - pyedaa-reports -v unittest "--merge=Any-JUnit:temp/junit/*.xml" "--output=pyTest-JUnit:report/unit/unittest.xml"
  artifacts:
    paths:
      - report/unit

Sphinx:
  stage: Documentation
  image: ${CI_REGISTRY}/docker-images/base-image:alpine
  needs:
    - job: MergeReports
      artifacts: true
  parallel:
    matrix:
      - SPHINX_BUILDER: ["html", "latex"]
  before_script:
    - pip install -U -r docs/requirements.txt
  script:
    - cd docs
    - sphinx-build --verbose --builder ${SPHINX_BUILDER} -d _build/doctrees --jobs 4 -w _build/${SPHINX_BUILDER}.log . _build/${SPHINX_BUILDER}
  artifacts:
    paths:
      - docs/_build/${SPHINX_BUILDER}

MikTeX:
  stage: Documentation
  image: ${CI_REGISTRY}/docker-images/miktex:sphinx
  needs:
    - job: Sphinx
      parallel:
        matrix:
          - SPHINX_BUILDER: "latex"
      artifacts: true
  script:
    - cd docs/_build/latex
    - exec-LaTeX.sh --xelatex "PoC.tex"
  after_script:
    - CopyFile docs/_build/latex/PoC.pdf .
  artifacts:
    paths:
      - ./*.pdf
  allow_failure: true


# ------------------
# ----- Pages ------
# ------------------
pages:
  stage: GitLabPages
  image: ${CI_REGISTRY}/docker-images/base-image:alpine
  parallel:
    matrix:
      - IMAGE:   "nvc"
        VERSION: "latest"
      - IMAGE:   "ghdl"
        VERSION: "llvm"
  needs:
    - job: PoC-sim  # main only
      artifacts: true
      parallel:
        matrix:
          - IMAGE:   $[[ matrix.IMAGE ]]
            VERSION: $[[ matrix.VERSION ]]
      optional: true
  rules:
    - if: >
        $SIMULATOR_PAGES == "$[[ matrix.IMAGE ]]" &&
        $CI_PIPELINE_SOURCE == "push" &&
        $CI_COMMIT_BRANCH =~ /^(main|master|dev)$/
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  pages: true
  before_script:
    - apk update
    - apk add tree
  script:
    - CopyDir docs/_build/html public
    #- CopyFile PoC.pdf  public
    - tree public
  after_script:
    - echo "Pages accessible at ${CI_PAGES_URL}"
  artifacts:
    paths:
      - public
