stages:
  - prepare
  - build_osvvm
  - build_poc
  - test
  - pages

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  SIMULATOR_PAGES: "NVC"  # simulator from which the results should be published on GitLab pages (GHDL, Riviera-PRO)

  # Names for specific jobs
  COMPILE_OSVVM_NAME  : "OsvvmLibraries"
  COMPILE_POC_NAME    : "PoC"
  SIMULATE_OSVVM_NAME : "OSVVM-RunAllTests"
  SIMULATE_POC_NAME   : "PoC-RunAllTests"

Scripts:
  stage: prepare
  image: ${CI_REGISTRY}/docker-images/base-image:alpine
  script:
    - mv src/common/my_project.vhdl.template tb/common/my_project.vhdl  # use CopyFile when its supporting renaming
    - sed -i 's#\(constant\sMY_PROJECT_DIR\s*:\s*string\s*:=\s*\)".*";#\1"'"$(pwd)"'";#' tb/common/my_project.vhdl
    - sed -i 's#\(constant\sMY_OPERATING_SYSTEM\s*:\s*string\s*:=\s*\)".*";#\1"LINUX";#' tb/common/my_project.vhdl

    - CreateAndChangeDirectory "temp" "Simulation working directory"
    - |
      tee setup_simulator.tcl <<EOF
      source ../../lib/OSVVM-Scripts/StartUp.tcl
      source ../../tools/OSVVM/poc.tcl
      namespace import ::poc::*
      # Skip report generation if executed within Sigasi/VS Code
      if {[info exists ::env(OSVVM_TOOL)] && $::env(OSVVM_TOOL) eq "Sigasi"} {
        set ::osvvm::GenerateOsvvmReports "false"
      }
      if {[info exists ::env(GITLAB_CI)]} {
        set buildNamePrefix ""
      } else {
        set buildNamePrefix "\${::osvvm::ToolNameVersion}-"
      }
      # -g -gui         disables system exit (i.e. on errors)
      # -v -vendor      Vendor name
      # -b -board       Board name
      # -p -projectFile Path to the my_project file
      # -c -configFile  Path to the my_config file
      configurePoC
      # -s -stop <i>    set the stop counts to <i>
      # -d -debug       enable debugging
      # -w -waves       save waveforms
      configureOSVVM
      EOF

      tee eval_prefix.tcl <<EOF
      source ../setup_simulator.tcl
      puts -nonewline $::poc::buildNamePrefix
      EOF

      tee osvvm_compile.tcl <<EOF
      source ../setup_simulator.tcl
      build ../../lib/OsvvmLibraries.pro [BuildName "\${::poc::buildNamePrefix}${COMPILE_OSVVM_NAME}"]
      checkForBuildErrors
      EOF

      tee poc_compile.tcl <<EOF
      source ../setup_simulator.tcl
      build ../../src/build.pro [BuildName "\${::poc::buildNamePrefix}${COMPILE_POC_NAME}"]
      checkForBuildErrors
      EOF

      tee osvvm_sim.tcl <<EOF
      source ../setup_simulator.tcl
      build ../../lib/RunAllTests.pro [BuildName "\${::poc::buildNamePrefix}${SIMULATE_OSVVM_NAME}"]
      checkForRunErrors
      EOF

      tee poc_sim.tcl <<EOF
      source ../setup_simulator.tcl
      build ../../tb/RunAllTests.pro [BuildName "\${::poc::buildNamePrefix}${SIMULATE_POC_NAME}"]
      checkForRunErrors
      EOF

  artifacts:
    paths:
      - tb/common/my_project.vhdl
      - temp/*.tcl
    expire_in: 1 hour


# --------------------
# ---- Templates -----
# --------------------
.SimulationWrapper:
  before_script:
    - |
      if [ "$SIMULATOR" = "NVC" ]; then
        CreateAndChangeDirectory "temp/NVC" "Simulation working directory"
        export buildNamePrefix=$(nvc --do ../eval_prefix.tcl | tail -n 1 | sed 's/^#\s*//')
      else
        export buildNamePrefix=$(exec-$SIMULATOR.sh -n --tcl-file=temp/eval_prefix.tcl | tail -n 1 | sed 's/^#\s*//')
      fi
    - FullBuildName="${buildNamePrefix}${RESULT_NAME}"
    - echo "Full buildname is $FullBuildName"
    - echo "$FullBuildName" > $CI_PROJECT_DIR/temp/$SIMULATOR/full_build_name.txt
  after_script:
    - FullBuildName=$(cat temp/$SIMULATOR/full_build_name.txt)
    - mkdir -p temp/junit
    - CopyFile "temp/$SIMULATOR/$FullBuildName/$FullBuildName.xml" "temp/junit"
    - CopyFile "temp/$SIMULATOR/$FullBuildName/$FullBuildName.yml" "temp/junit"

.compile:
  extends:
    - .SimulationWrapper
  script:
    - |
      if [ "$SIMULATOR" = "NVC" ]; then
        # before_script and script are running in the same shell; therefore no need to change the directory
        nvc --do ../${TCL_FILE}
      else
        exec-$SIMULATOR.sh -n --tcl-file=temp/${TCL_FILE}
      fi
  artifacts:
    paths:
      - temp/$SIMULATOR
      - temp/junit
      - lib/osvvm/*_generated.vhd
    expire_in: 1 week
    when: always

.simulate:
  extends:
    - .SimulationWrapper
  script:
    - |
      if [ "$SIMULATOR" = "NVC" ]; then
        # before_script and script are running in the same shell; therefore no need to change the directory
        nvc --do ../${TCL_FILE}
      else
        exec-$SIMULATOR.sh -n --tcl-file=temp/${TCL_FILE}
      fi
  allow_failure: true  # if case the Riviera license is in use
  artifacts:
    paths:
      - temp/junit
      - temp/$SIMULATOR
    reports:
      junit: "temp/junit/*.xml"
    expire_in: 1 week
    when: always

# ---------------
# ---- GHDL -----
# ---------------
.GHDL:
  parallel:
    matrix:
      - GHDL_BACKEND: ["llvm", "mcode"]
  image: ${CI_REGISTRY}/docker-images/ghdl:${GHDL_BACKEND}
  variables:
    SIMULATOR: "GHDL"

GHDL_OSVVM_compile:
  stage: build_osvvm
  extends:
    - .GHDL
    - .compile
  needs:
    job: Scripts
    artifacts: true
  variables:
    TCL_FILE: "osvvm_compile.tcl"

GHDL_PoC_compile:
  stage: build_poc
  extends:
    - .GHDL
    - .compile
  needs:
    - job: Scripts
      artifacts: true
    - job: GHDL_OSVVM_compile
      artifacts: true
  variables:
    TCL_FILE: "poc_compile.tcl"
    RESULT_NAME: "$COMPILE_POC_NAME"

GHDL_OSVVM_sim:
  stage: test
  extends:
    - .GHDL
    - .simulate
  needs:
    - job: Scripts
      artifacts: true
    - job: GHDL_OSVVM_compile
      artifacts: true
  only:
    - main
    - master
    - dev
  variables:
    TCL_FILE: "osvvm_sim.tcl"
    RESULT_NAME: "$SIMULATE_OSVVM_NAME"

GHDL_PoC_sim:
  stage: test
  extends:
    - .GHDL
    - .simulate
  needs:
    - job: Scripts
      artifacts: true
    - job: GHDL_PoC_compile
      artifacts: true
  variables:
    TCL_FILE: "poc_sim.tcl"
    RESULT_NAME: "$SIMULATE_POC_NAME"

# ------------------
# ---- Riviera -----
# ------------------
.RIVIERA-PRO:
  image: ${CI_REGISTRY}/docker-images/rivierapro:2024.10
  variables:
    SIMULATOR: "Riviera-PRO"

RIVIERA_OSVVM_compile:
  stage: build_osvvm
  extends:
    - .RIVIERA-PRO
    - .compile
  needs:
    job: Scripts
    artifacts: true
  variables:
    TCL_FILE: "osvvm_compile.tcl"
    RESULT_NAME: "$COMPILE_OSVVM_NAME"

RIVIERA_PoC_compile:
  stage: build_poc
  extends:
    - .RIVIERA-PRO
    - .compile
  needs:
    - job: Scripts
      artifacts: true
    - job: RIVIERA_OSVVM_compile
      artifacts: true
  variables:
    TCL_FILE: "poc_compile.tcl"
    RESULT_NAME: "$COMPILE_POC_NAME"

RIVIERA_OSVVM_sim:
  stage: test
  extends:
    - .RIVIERA-PRO
    - .simulate
  needs:
    - job: Scripts
      artifacts: true
    - job: RIVIERA_OSVVM_compile
      artifacts: true
    - job: RIVIERA_PoC_compile  # avoid license blocking
      artifacts: true
  only:
    - main
    - master
    - dev
  allow_failure: true
  variables:
    TCL_FILE: "osvvm_sim.tcl"
    RESULT_NAME: "$SIMULATE_OSVVM_NAME"

RIVIERA_PoC_sim:
  stage: test
  extends:
    - .RIVIERA-PRO
    - .simulate
  needs:
    - job: Scripts
      artifacts: true
    - job: RIVIERA_PoC_compile
      artifacts: true
    - job: RIVIERA_OSVVM_sim  # avoid license blocking
      optional: true
      artifacts: false
  variables:
    TCL_FILE: "poc_sim.tcl"
    RESULT_NAME: "$SIMULATE_POC_NAME"


# --------------
# ---- NVC -----
# --------------
.NVC:
  image: ${CI_REGISTRY}/docker-images/nvc:latest
  variables:
    SIMULATOR: "NVC"

NVC_OSVVM_compile:
  stage: build_osvvm
  extends:
    - .NVC
    - .compile
  needs:
    job: Scripts
    artifacts: true
  variables:
    TCL_FILE: "osvvm_compile.tcl"
    RESULT_NAME: "$COMPILE_OSVVM_NAME"

NVC_PoC_compile:
  stage: build_poc
  extends:
    - .NVC
    - .compile
  needs:
    - job: Scripts
      artifacts: true
    - job: NVC_OSVVM_compile
      artifacts: true
  variables:
    TCL_FILE: "poc_compile.tcl"
    RESULT_NAME: "$COMPILE_POC_NAME"

NVC_OSVVM_sim:
  stage: test
  extends:
    - .NVC
    - .simulate
  needs:
    - job: Scripts
      artifacts:
    - job: NVC_OSVVM_compile
      artifacts: true
  only:
    - main
    - master
    - dev
  variables:
    TCL_FILE: "osvvm_sim.tcl"
    RESULT_NAME: "$SIMULATE_OSVVM_NAME"

NVC_PoC_sim:
  stage: test
  extends:
    - .NVC
    - .simulate
  needs:
    - job: Scripts
      artifacts: true
    - job: NVC_PoC_compile
      artifacts: true
  variables:
    TCL_FILE: "poc_sim.tcl"
    RESULT_NAME: "$SIMULATE_POC_NAME"


# --------------------------
# ----- Documentation ------
# --------------------------
MergeReports:
  stage: test
  image: ${CI_REGISTRY}/docker-images/base-image:alpine
  needs:
    - job: GHDL_PoC_sim
      artifacts: true
    - job: RIVIERA_PoC_sim
      artifacts: true
    - job: NVC_PoC_sim
      artifacts: true
  before_script:
    - pip install pyEDAA.Reports
  script:
    - mkdir -p report/unit
    - pyedaa-reports -v unittest "--merge=Any-JUnit:temp/junit/*.xml" "--output=pyTest-JUnit:report/unit/unittest.xml"
    - mv temp/junit/${SIMULATOR_PAGES}-PoC.yml report/unit/osvvmreport.yml
  artifacts:
    paths:
      - report/unit

Sphinx:
  stage: pages
  image: ${CI_REGISTRY}/docker-images/base-image:alpine
  needs:
    - job: MergeReports
      artifacts: true
  parallel:
    matrix:
      - SPHINX_BUILDER: ["html", "latex"]
  before_script:
    - pip install -U -r docs/requirements.txt
  script:
    - cd docs
    - sphinx-build --verbose --builder ${SPHINX_BUILDER} -d _build/doctrees --jobs 4 -w _build/${SPHINX_BUILDER}.log . _build/${SPHINX_BUILDER}
  artifacts:
    paths:
      - docs/_build/${SPHINX_BUILDER}

MikTeX:
  stage: pages
  needs:
    - job: Sphinx
      parallel:
        matrix:
          - SPHINX_BUILDER: "latex"
      artifacts: true
  image: ${CI_REGISTRY}/docker-images/miktex:sphinx
  script:
    - cd docs/_build/latex
    - exec-LaTeX.sh --xelatex "PoC.tex"
  after_script:
    - CopyFile docs/_build/latex/PoC.pdf .
  artifacts:
    paths:
      - ./*.pdf
  allow_failure: true


# ------------------
# ----- Pages ------
# ------------------
.pages:
  image: ${CI_REGISTRY}/docker-images/base-image:alpine
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  pages: true
  before_script:
    - apk update
    - apk add tree
  script:
    - CopyDir docs/_build/html       public
    #- CopyFile PoC.pdf  public
    - tree public
  after_script:
    - echo "Pages accessible at ${CI_PAGES_URL}"
  artifacts:
    paths:
      - public


pagesGHDL:
  stage: pages
  rules:
    - if: >
        $SIMULATOR_PAGES == "GHDL" &&
        $CI_PIPELINE_SOURCE == "push" &&
        $CI_COMMIT_BRANCH =~ /^(main|master|dev)$/
  needs:
    - job: GHDL_OSVVM_sim  # main only
      artifacts: true
      optional: true
    - job: GHDL_PoC_sim
      artifacts: true
      optional: true
  extends:
    - .pages

pagesRiviera:
  stage: pages
  rules:
    - if: >
        $SIMULATOR_PAGES == "Riviera-PRO" &&
        $CI_PIPELINE_SOURCE == "push" &&
        $CI_COMMIT_BRANCH =~ /^(main|master|dev)$/
  needs:
    - job: RIVIERA_PoC_sim  # inherits artifacts from previous jobs
      artifacts: true
      optional: true
  extends:
    - .pages

pagesNVC:
  stage: pages
  extends:
    - .pages
  rules:
    - if: >
        $SIMULATOR_PAGES == "NVC" &&
        $CI_PIPELINE_SOURCE == "push"
  needs:
    - job: NVC_OSVVM_sim
      artifacts: true
      optional: true
    - job: NVC_PoC_sim
      artifacts: true
      optional: true
    - job: Sphinx
      artifacts: true
