/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __ite_traceEth_TraceEth__
#define __ite_traceEth_TraceEth__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jbyteArray JNICALL Java_ite_traceEth_TraceEth_sendAndReceive (JNIEnv *env, jclass, jbyteArray);
JNIEXPORT void JNICALL Java_ite_traceEth_TraceEth_initialize (JNIEnv *env, jclass);
JNIEXPORT void JNICALL Java_ite_traceEth_TraceEth_initializeTraceReceiver (JNIEnv *env, jclass, jstring, jbyteArray);
JNIEXPORT void JNICALL Java_ite_traceEth_TraceEth_finish (JNIEnv *env, jclass);
JNIEXPORT void JNICALL Java_ite_traceEth_TraceEth_flush (JNIEnv *env, jclass);

#undef ite_traceEth_TraceEth_bufferLength
#define ite_traceEth_TraceEth_bufferLength 1300L

#ifdef __cplusplus
}
#endif

#endif /* __ite_traceEth_TraceEth__ */
