#!/usr/bin/python
# EMACS settings: -*-  tab-width: 2; indent-tabs-mode: t; python-indent-offset: 2 -*-
# vim: tabstop=2:shiftwidth=2:noexpandtab
# kate: tab-width 2; replace-tabs off; indent-width 2;
#
# ==============================================================================
# Authors:               Thomas B. Preusser
#
# License:
# ==============================================================================
# Copyright 2007-2016 Technische Universitaet Dresden - Germany
#                     Chair for VLSI-Design, Diagnostics and Architecture
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# distributed under the License is distributed on an "AS IS" BASIS,default
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

"""
This hook checks reST files for headline markers that coincide with git
conflict markers and could cause issues in future merge operations. It replaces all
lines consisting solely of 7x'=' by 8x'='.
"""
from subprocess import check_output, check_call
import fileinput

# Normalize staged reST files
staged = check_output(['git', 'diff', '--name-only', '--cached'], universal_newlines=True).strip()
for file in staged.split('\n'):
	file = file.strip()
	if file.endswith('.rst'):
		changed = 0
		for line in fileinput.input(file, inplace=True):
			line = line.rstrip('\n\r')
			if line == '='*7:
				line = '='*8
				changed = changed + 1
			print(line)
		if changed:
			print('  %s: changed %d headline markers.'%(file, changed))
			check_call(['git', 'add', file ])
