

$ARCHITECTURE =			x86_64

$ROOT_DIRECTORY =		G:\git\PoC\lib\cocotb
$INCLUDE_DIRECTORY = $ROOT_DIRECTORY\include
$BUILD_DIRECTORY =	$ROOT_DIRECTORY\build
$OBJECT_DIRECTORY =	$BUILD_DIRECTORY\obj\$ARCHITECTURE
$SHARED_DIRECTORS = $BUILD_DIRECTORY\libs\$ARCHITECTURE

$COCOTB_INCLUDE = -I$INCLUDE_DIRECTORY

$PY_VERSION = "2.7"
$PY_LIBRARY = "python$PY_VERSION"
$PYTHON_DEF = "-DPYTHON_SO_LIB=lib$PY_LIBRARY.so"
$PYTHON_INC = -I/usr/include/$PY_LIBRARY
$PYTHON_LIB = "-l$PY_LIBRARY"

# $VSIM_INCLUDE = /opt/questasim/10.4d/bin/../include
$VSIM_INCLUDE = C:\Altera\16.0\modelsim_ase\include

$GCC_WARNINGS1 = -Werror -Wcast-qual -Wcast-align -Wwrite-strings -Wall -Wno-unused-parameter
$GCC_WARNINGS2 = -Wstrict-prototypes -Waggregate-return
$GCC_DEBUG = -g -DDEBUG
$GCC_DEFINES = -DMODELSIM
$GCC_FLAGS = -fno-common -fpic

$GCC_INCLUDE = -I/usr/include/x86_64-linux-gnu
$GCC_LIBRARY = -L/usr/lib

$GCC_INCLUDES = $GCC_INCLUDE $PYTHON_INC $COCOTB_INCLUDE
$GPP_INCLUDES = $PYTHON_INC $COCOTB_INCLUDE



$GCC_LIBRARIES = $GCC_LIBRARY
gcc -v -c      $GCC_WARNINGS1 $GCC_FLAGS $GCC_DEBUG $GCC_DEFINES1                        $GCC_INCLUDES              -o $OBJECT_DIRECTORY\cocotb_utils.o cocotb_utils.c
gcc -v -c      $GCC_WARNINGS1 $GCC_FLAGS $GCC_DEBUG $GCC_DEFINES1 $GCC_WARNING2          $GCC_INCLUDES              -o $OBJECT_DIRECTORY\cocotb_utils.o cocotb_utils.c
gcc -v -shared $GCC_WARNINGS1 $GCC_FLAGS $GCC_DEBUG $GCC_DEFINES1 $GCC_WARNING2 -Xlinker $GCC_LIBRARIES             -o $SHARED_DIRECTORY\libcocotbutils.so $OBJECT_DIRECTORY\cocotb_utils.o

$GCC_LIBRARIES = $GCC_LIBRARY -lpthread -ldl -lutil -lm
gcc -v -c      $GCC_WARNINGS1 $GCC_FLAGS $GCC_DEBUG $GCC_DEFINES1 $GCC_WARNING2 -DFILTER $GCC_INCLUDES              -o $OBJECT_DIRECTORY\gpi_logging.o gpi_logging.c
gcc -v -shared $GCC_WARNINGS1 $GCC_FLAGS $GCC_DEBUG $GCC_DEFINES1 $GCC_WARNING2 -DFILTER -Xlinker $GCC_LIBRARIES $PYTHON_LIB -o $SHARED_DIRECTORY\libgpilog.so $OBJECT_DIRECTORY\gpi_logging.o

$GCC_LIBRARIES = $GCC_LIBRARY -lpthread -ldl -lutil -lm -lgpilog -lcocotbutils
gcc -v -c      $GCC_WARNINGS1 $GCC_FLAGS $GCC_DEBUG $GCC_DEFINES1 $GCC_WARNING2 $PYTHON_DEF $GCC_INCLUDES           -o $OBJECT_DIRECTORY\gpi_embed.o gpi_embed.c
gcc -v -shared $GCC_WARNINGS1 $GCC_FLAGS $GCC_DEBUG $GCC_DEFINES1 $GCC_WARNING2 $PYTHON_DEF -Xlinker $GCC_LIBRARIES -o $SHARED_DIRECTORY\libcocotb.so $OBJECT_DIRECTORY\gpi_embed.o $PYTHON_LIB -L$SHARED_DIRECTORY

$GCC_LIBRARIES = $GCC_LIBRARY -lstdc++ -lgpilog -lcocotbutils -lcocotb
g++ -v -c      $GCC_WARNINGS1 $GCC_FLAGS $GCC_DEBUG $GCC_DEFINES1 -DVPI_CHECKING -DLIB_EXT=so -DSINGLETON_HANDLES $GPP_INCLUDES           -o $OBJECT_DIRECTORY\GpiCbHdl.o  GpiCbHdl.cpp
g++ -v -c      $GCC_WARNINGS1 $GCC_FLAGS $GCC_DEBUG $GCC_DEFINES1 -DVPI_CHECKING -DLIB_EXT=so -DSINGLETON_HANDLES $GPP_INCLUDES           -o $OBJECT_DIRECTORY\GpiCommon.o GpiCommon.cpp
gcc -v -shared $GCC_WARNINGS1 $GCC_FLAGS $GCC_DEBUG $GCC_DEFINES1 -DVPI_CHECKING -DLIB_EXT=so -DSINGLETON_HANDLES $GCC_WARNING2 -Xlinker $GCC_LIBRARIES -o $SHARED_DIRECTORY\libgpi.so  $OBJECT_DIRECTORY\GpiCbHdl.o $OBJECT_DIRECTORY\GpiCommon.o -L$SHARED_DIRECTORY

$GCC_LIBRARIES = $GCC_LIBRARY -lpthread -ldl -lutil -lm -lgpi -lgpilog
gcc -v -c      $GCC_WARNINGS1 $GCC_FLAGS $GCC_DEBUG $GCC_DEFINES1 $GCC_WARNING2 $GCC_INCLUDES  -o $OBJECT_DIRECTORY\simulatormodule.o simulatormodule.c -I/usr/include/x86_64-linux-gnu
gcc -v -shared $GCC_WARNINGS1 $GCC_FLAGS $GCC_DEBUG $GCC_DEFINES1 $GCC_WARNING2 -Xlinker $GCC_LIBRARIES -o $SHARED_DIRECTORY\libsim.so $OBJECT_DIRECTORY\simulatormodule.o $PYTHON_LIB -L$SHARED_DIRECTORY

ln -sf libsim.so $SHARED_DIRECTORY\simulator.so

$GCC_LIBRARIES = $GCC_LIBRARY -lstdc++ -lgpi -lgpilog
g++ -v -c      $GCC_WARNINGS1 $GCC_FLAGS $GCC_DEBUG $GCC_DEFINES1 -DVPI_CHECKING $GPP_INCLUDES                     -o $OBJECT_DIRECTORY\VpiImpl.o  VpiImpl.cpp
g++ -v -c      $GCC_WARNINGS1 $GCC_FLAGS $GCC_DEBUG $GCC_DEFINES1 -DVPI_CHECKING $GPP_INCLUDES                     -o $OBJECT_DIRECTORY\VpiCbHdl.o VpiCbHdl.cpp
gcc -v -shared $GCC_WARNINGS1 $GCC_FLAGS $GCC_DEBUG $GCC_DEFINES1 -DVPI_CHECKING $GCC_WARNING2 -Xlinker $GCC_LIBRARIES -o $SHARED_DIRECTORY\libvpi.so $OBJECT_DIRECTORY\VpiImpl.o $OBJECT_DIRECTORY\VpiCbHdl.o -L$SHARED_DIRECTORY

$GPP_INCLUDES = $PYTHON_INC $COCOTB_INCLUDE $VSIM_INCLUDE
$GCC_LIBRARIES = $GCC_LIBRARY -lstdc++ -lgpi -lgpilog
g++ -v -c      $GCC_WARNINGS1 $GCC_FLAGS $GCC_DEBUG $GCC_DEFINES1 -DFLI_CHECKING -DUSE_CACHE $GPP_INCLUDES -o $OBJECT_DIRECTORY\FliImpl.o FliImpl.cpp
g++ -v -c      $GCC_WARNINGS1 $GCC_FLAGS $GCC_DEBUG $GCC_DEFINES1 -DFLI_CHECKING -DUSE_CACHE $GPP_INCLUDES -o $OBJECT_DIRECTORY\FliCbHdl.o FliCbHdl.cpp
g++ -v -c      $GCC_WARNINGS1 $GCC_FLAGS $GCC_DEBUG $GCC_DEFINES1 -DFLI_CHECKING -DUSE_CACHE $GPP_INCLUDES -o $OBJECT_DIRECTORY\FliObjHdl.o FliObjHdl.cpp
gcc -v -shared $GCC_WARNINGS1 $GCC_FLAGS $GCC_DEBUG $GCC_DEFINES1 -DFLI_CHECKING -DUSE_CACHE $GCC_WARNING2 -Xlinker $GCC_LIBRARIES -o $SHARED_DIRECTORY\libfli.so  $OBJECT_DIRECTORY\FliImpl.o $OBJECT_DIRECTORY\FliCbHdl.o $OBJECT_DIRECTORY\FliObjHdl.o -L$SHARED_DIRECTORY






