.. # Load pre-defined aliases and graphical characters like © from docutils
   # <file> is used to denote the special path
   # <Python>\Lib\site-packages\docutils\parsers\rst\include
.. include:: <isonum.txt>
.. include:: <mmlalias.txt>

.. # define a hard line break for HTML
.. |br| raw:: html

   <br />

.. # define horizontal line for HTML
.. |hr| raw:: html

   <hr />

.. role:: bolditalic
   :class: bolditalic

.. role:: underline
   :class: underline

.. role:: strike
   :class: strike

.. role:: xlarge
   :class: xlarge

.. role:: red
   :class: colorred
.. role:: green
   :class: colorgreen
.. role:: blue
   :class: colorblue
.. role:: purple
   :class: colorpurple

.. role:: deletion
   :class: colorred strike
.. role:: addition
   :class: colorgreen

.. role:: comp
   :class: componentname
.. role:: generic
   :class: genericname
.. role:: port
   :class: portname
.. role:: pack
   :class: packagename
.. role:: type
   :class: typename
.. role:: subprog
   :class: subprogramname
.. role:: value
   :class: value

.. role:: pycode(code)
   :language: python
   :class: highlight

.. role:: vhdlcode(code)
   :language: vhdl
   :class: highlight
