.. # Use http://b64.io/ to encode any image to base64. Then replace `/` with
   # `%2F` and `+` with `%2B` (or use http://meyerweb.com/eric/tools/dencoder/).
   # Beware that `?logo=data:image/png;base64,` must also be converted to
   # percent encoding so that the URL is properly parsed.

.. # Sourcecode link to GitHub
.. |SHIELD:svg:PoC-github| image:: https://img.shields.io/badge/VHDL-PoC-63bf7f?longCache=true&style=flat-square&longCache=true&logo=GitHub
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/VHDL/PoC
.. |SHIELD:png:PoC-github| image:: https://raster.shields.io/badge/VHDL-PoC-63bf7f?longCache=true&style=flat-square&longCache=true&logo=GitHub
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/VHDL/PoC

.. # Sourcecode license
.. |SHIELD:svg:PoC-src-license| image:: https://img.shields.io/pypi/l/PoC?longCache=true&style=flat-square&logo=Apache&label=code
   :alt: Code license
   :height: 22
   :target: License.html
.. |SHIELD:png:PoC-src-license| image:: https://img.shields.io/pypi/l/PoC?longCache=true&style=flat-square&logo=Apache&label=code
   :alt: Code license
   :height: 22
   :target: https://GitHub.com/VHDL/PoC/blob/main/LICENSE.md

.. # GitHub tag
.. |SHIELD:svg:PoC-tag| image:: https://img.shields.io/github/v/tag/VHDL/PoC?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://GitHub.com/VHDL/PoC/tags
.. |SHIELD:png:PoC-tag| image:: https://raster.shields.io/github/v/tag/VHDL/PoC?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://GitHub.com/VHDL/PoC/tags

.. # GitHub release date
.. |SHIELD:svg:PoC-date| image:: https://img.shields.io/github/release-date/VHDL/PoC?longCache=true&style=flat-square&logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://GitHub.com/VHDL/PoC/releases
.. |SHIELD:png:PoC-date| image:: https://raster.shields.io/github/release-date/VHDL/PoC?longCache=true&style=flat-square&logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://GitHub.com/VHDL/PoC/releases


.. # Documentation license
.. |SHIELD:svg:PoC-doc-license| image:: https://img.shields.io/badge/doc-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: Doc-License.html
.. |SHIELD:png:PoC-doc-license| image:: https://raster.shields.io/badge/doc-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: https://GitHub.com/VHDL/PoC/blob/main/docs/Doc-License.rst

.. # GHPages - read now
.. |SHIELD:svg:PoC-ghp-doc| image:: https://img.shields.io/website?longCache=true&style=flat-square&label=VHDL.github.io%2FPoC&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2FpyTooling.github.io%2FpyTooling%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://VHDL.github.io/PoC/
.. |SHIELD:png:PoC-ghp-doc| image:: https://raster.shields.io/website?longCache=true&style=flat-square&label=VHDL.github.io%2FPoC&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2FpyTooling.github.io%2FpyTooling%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://VHDL.github.io/PoC/
